# Generated by Django 3.0.5 on 2020-07-07 21:35

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateTimeField()),
                ('videos', djongo.models.fields.EmbeddedField(model_container=api.models.video)),
                ('imagenes', djongo.models.fields.EmbeddedField(model_container=api.models.imagen)),
            ],
        ),
    ]
