FROM phusion/baseimage:0.9.15

ENV HOME /root

RUN apt-get update -q

RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

RUN chpasswd -e

ADD bashrc /root/.bashrc
ADD timezone /etc/timezone

EXPOSE 22

CMD ["/sbin/my_init"]
