version: '3.7'

services:
    web:
        build: ./ActualizaStreet
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./ActualizaStreet/:/usr/src/ActualizaStreet/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev

    
            