# Generated by Django 3.0.5 on 2020-07-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nrol', models.CharField(db_column='nRol', max_length=30)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('nusuario', models.CharField(db_column='nUsuario', max_length=50)),
                ('ausuario', models.CharField(db_column='aUsuario', max_length=50)),
                ('eusuario', models.CharField(db_column='eUsuario', max_length=100)),
                ('tusuario', models.IntegerField(db_column='tUsuario')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Validar',
            fields=[
                ('usuario', models.OneToOneField(db_column='Usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='users.Usuario')),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=16)),
            ],
            options={
                'db_table': 'Validar',
                'managed': False,
            },
        ),
    ]
